### ISSUE TITLE
natgrid setup for Python 3.x on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by mo-vellanki** [matplotlib/natgrid#2]
I could setup natgrid 0.2 on Windows 10.1 using conda and python 3.6 but the same on Ubuntu doesn't work because of the dependencies.

**Comment by phobson** [comment]
Can you provide some more details? Can you show the conda command and error message?

**Comment by mo-vellanki** [comment]
@phobson I run Ubuntu 16.04LTS and have the same version of Python(3.6) installed on Windows as well.

```
$ conda -V
conda 4.3.21
```


```
$  conda install -c jochym natgrid=0.2
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - natgrid 0.2* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.


```

**Comment by tacaswell** [comment]
This is an issue with the packaging from that channel who does not have python 3.6 binaries up.  Please contact the owner of that channel or check if conda-forge has a feedstock for this.
