### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jrwrigh** [matplotlib/natgrid#4]
The error in matplotlib that is probably responsible for 90% of the installations to this page says:

```
To use interp='nn' (Natural Neighbor interpolation) in griddata, natgrid must be installed. Either install it from http://github.com/matplotlib/natgrid
```

And yet their isn't a single installation instruction to be found. 

Treat people like they don't know what they're doing with a raw Python module. Because they (me) probably don't know what they're supposed to do with a raw python module.

**Comment by ImportanceOfBeingErnest** [comment]
If [`matplotlib.mlab.griddata`](https://matplotlib.org/api/mlab_api.html#matplotlib.mlab.griddata) brought you here, consider that it is deprecated according to its documentation:

> Deprecated since version 2.2: The griddata function was deprecated in Matplotlib 2.2 and will be removed in 3.1. Use [scipy.interpolate.griddata](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) instead.

and also

> Instead of using griddata, more flexible functionality and other interpolation options are available using a matplotlib.tri.Triangulation and a matplotlib.tri.TriInterpolator.

There is a matplotlib example showing this functionality in 
https://matplotlib.org/gallery/images_contours_and_fields/irregulardatagrid.html

<hr>

Else, it is probably assumed that users who need this package would find out [How to install a python module from github](https://www.google.com/search?q=install+python+module+from+github); in this case

    python -mpip install git+https://github.com/matplotlib/natgrid.git


Maybe worth noting that this package has last been updated in 2010. So it is not guaranteed to be working with newer python versions (though it still does in my experience).

**Comment by jrwrigh** [comment]
Thanks for the info! I actually just moved to scipy's `griddata` since I couldn't get matplotlib's version to work. It's working well now.

And thanks for the info on installing modules from git repos.
